[font]
  #size = 10.0
  normal = { family = "JetBrainsMonoNerdFontMono" }
  #normal = { family = "3270NerdFontMono", style = "Condensed" }
[window]
  opacity = 0.8
  dynamic_padding = true

[mouse]
  bindings = [
    { mouse = "Middle", action = "PasteSelection" }
  ]
